name: pgnpartner_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+46

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  build_runner: ^2.4.11
  cached_network_image: ^3.4.0
  carousel_slider: ^5.0.0
  crypto: ^3.0.3
  cryptography: ^2.7.0
  dio: ^5.5.0+1
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: ^1.1.3+2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  flutter_switch: ^0.3.2
  geocoding: ^3.0.0
  get: ^4.6.6
  google_maps_flutter: ^2.9.0
  http: ^1.2.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  local_auth: ^2.3.0
  location: ^7.0.1
  mobile_scanner: ^4.0.0
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  pinenacl: ^0.6.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  signature: ^5.5.0
  sqflite: ^2.3.2
  syncfusion_flutter_datepicker: ^26.2.5
  syncfusion_localizations: ^26.2.5

dev_dependencies:
  faker: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/img_app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/svg/navigation/
    - assets/icons/
    # - assets/others/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter_18pt-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter_18pt-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter_18pt-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter_18pt-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter_18pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_18pt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter_18pt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter_18pt-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter/Inter_18pt-BlackItalic.ttf
          weight: 900
          style: italic
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
